import Bennett.Uncompute.Core
import Lean.Elab.Tactic.Omega

/-!
# Abstract reversible checkpoint chains

This module separates segmented checkpointing from any tape machine.
The first layer is a generic five-stage checkpoint macro and a checked
`HistoryRecorder` specialization that erases every primary-history record
generated by a segment.
The second, independent layer commits complete restart checkpoints and
composes a finite list of segment partial computations.  No resource cost is
assigned here.
-/

namespace Bennett.Checkpoint

open Bennett.Uncompute

variable {Permanent Scratch Dump Left Right : Type*}

/-- Lift a partial equivalence through an untouched left register. -/
def liftLeft (Register : Type*) (equiv : Left ≃. Right) :
    (Register × Left) ≃. (Register × Right) where
  toFun input := (equiv input.2).map fun output => (input.1, output)
  invFun output := (equiv.symm output.2).map fun input => (output.1, input)
  inv input output := by
    rcases input with ⟨register, left⟩
    rcases output with ⟨register', right⟩
    simp only [Option.map_eq_some_iff]
    constructor
    · rintro ⟨input, hinput, hp⟩
      have hregister : register' = register := congrArg Prod.fst hp
      have hleft : input = left := congrArg Prod.snd hp
      subst register'
      subst input
      exact ⟨right, (equiv.eq_some_iff.mp hinput), rfl⟩
    · rintro ⟨output, houtput, hp⟩
      have hregister : register = register' := congrArg Prod.fst hp
      have hright : output = right := congrArg Prod.snd hp
      subst register'
      subst output
      exact ⟨left, (equiv.eq_some_iff.mpr houtput), rfl⟩

@[simp] theorem liftLeft_apply (Register : Type*) (equiv : Left ≃. Right)
    (register : Register) (left : Left) :
    liftLeft Register equiv (register, left) =
      (equiv left).map fun right => (register, right) :=
  rfl

@[simp] theorem liftLeft_symm_apply (Register : Type*)
    (equiv : Left ≃. Right) (register : Register) (right : Right) :
    (liftLeft Register equiv).symm (register, right) =
      (equiv.symm right).map fun left => (register, left) :=
  rfl

/-- Internal shape of one checkpoint stage. -/
abbrev Frame (Permanent Scratch Dump : Type*) :=
  (Permanent × Scratch) × Dump

/--
Load a scratch value from permanent data, run a reversible segment, copy an
observation of its endpoint into a blank dump, uncompute, and unload scratch.
-/
def stage [DecidableEq Scratch] [DecidableEq Dump]
    (load : Permanent → Scratch) (observe : Scratch → Dump)
    (blankScratch : Scratch) (blankDump : Dump)
    (segment : Scratch ≃. Scratch) :
    Frame Permanent Scratch Dump ≃. Frame Permanent Scratch Dump :=
  let loadScratch :=
    liftRight (Bennett.Copy.observedEquiv load blankScratch) Dump
  let runSegment := liftRight (liftLeft Permanent segment) Dump
  let copyDump :=
    Bennett.Copy.observedEquiv
      (fun work : Permanent × Scratch => observe work.2) blankDump
  ((((loadScratch.trans runSegment).trans copyDump).trans runSegment.symm).trans
    loadScratch.symm)

/-- Exact stage endpoint, including complete temporary-scratch cleanup. -/
theorem stage_apply_of_segment [DecidableEq Scratch] [DecidableEq Dump]
    (load : Permanent → Scratch) (observe : Scratch → Dump)
    (blankScratch : Scratch) (blankDump : Dump)
    (segment : Scratch ≃. Scratch) (permanent : Permanent)
    (terminal : Scratch)
    (hsegment : segment (load permanent) = some terminal) :
    stage load observe blankScratch blankDump segment
        ((permanent, blankScratch), blankDump) =
      some ((permanent, blankScratch), observe terminal) := by
  have hinverse : segment.symm terminal = some (load permanent) :=
    segment.eq_some_iff.mpr hsegment
  let loadScratch :=
    liftRight (Bennett.Copy.observedEquiv load blankScratch) Dump
  let runSegment := liftRight (liftLeft Permanent segment) Dump
  let copyDump :=
    Bennett.Copy.observedEquiv
      (fun work : Permanent × Scratch => observe work.2) blankDump
  have hload : loadScratch ((permanent, blankScratch), blankDump) =
      some ((permanent, load permanent), blankDump) := by
    simp [loadScratch, Bennett.Copy.observedEquiv,
      Bennett.Copy.observedForward]
  have hrun : runSegment ((permanent, load permanent), blankDump) =
      some ((permanent, terminal), blankDump) := by
    simp [runSegment, hsegment]
  have hcopy : copyDump ((permanent, terminal), blankDump) =
      some ((permanent, terminal), observe terminal) := by
    simp [copyDump, Bennett.Copy.observedEquiv,
      Bennett.Copy.observedForward]
  have hunrun : runSegment.symm
      ((permanent, terminal), observe terminal) =
      some ((permanent, load permanent), observe terminal) := by
    simp [runSegment, hinverse]
  have huncopy :
      (Bennett.Copy.observedEquiv load blankScratch).symm
          (permanent, load permanent) =
        some (permanent, blankScratch) := by
    change Bennett.Copy.observedBackward load blankScratch
      (permanent, load permanent) = some (permanent, blankScratch)
    exact Bennett.Copy.observedBackward_apply_copy load blankScratch permanent
  have hunload : loadScratch.symm
      ((permanent, load permanent), observe terminal) =
      some ((permanent, blankScratch), observe terminal) := by
    simp [loadScratch, huncopy]
  change (((((loadScratch ((permanent, blankScratch), blankDump)).bind
      runSegment).bind copyDump).bind runSegment.symm).bind
        loadScratch.symm) = _
  simp [hload, hrun, hcopy, hunrun, hunload]

/-- The inverse verifies and deletes the dump, restoring both known blanks. -/
theorem stage_symm_cleanup_of_segment
    [DecidableEq Scratch] [DecidableEq Dump]
    (load : Permanent → Scratch) (observe : Scratch → Dump)
    (blankScratch : Scratch) (blankDump : Dump)
    (segment : Scratch ≃. Scratch) (permanent : Permanent)
    (terminal : Scratch)
    (hsegment : segment (load permanent) = some terminal) :
    (stage load observe blankScratch blankDump segment).symm
        ((permanent, blankScratch), observe terminal) =
      some ((permanent, blankScratch), blankDump) := by
  apply (stage load observe blankScratch blankDump segment).eq_some_iff.mpr
  exact stage_apply_of_segment load observe blankScratch blankDump segment
    permanent terminal hsegment

/-! ## Recorded implementation of one irreversible segment -/

/-- Implement one source segment with primary step-by-step history. The
    permanent value and copied dump are complete source checkpoints; the
    `HistoryState` exists only in scratch and is restored to `blankScratch`. -/
def recordedSegmentStage {Alpha Record : Type*} {step : PartialStep Alpha}
    [DecidableEq Alpha] [DecidableEq Record]
    (recorder : HistoryRecorder step Record)
    (blankScratch : HistoryState Alpha Record) (blankDump : Alpha)
    (length : Nat) :
    Frame Alpha (HistoryState Alpha Record) Alpha ≃.
      Frame Alpha (HistoryState Alpha Record) Alpha :=
  stage
    (fun checkpoint : Alpha =>
      (⟨checkpoint, []⟩ : HistoryState Alpha Record))
    (fun state : HistoryState Alpha Record => state.current)
    blankScratch blankDump (recordedEquivAt recorder length)

/-- A source run lifts to recorded execution, copies its complete terminal
    checkpoint, reverses every recorded step, and erases all history records
    generated by the segment. The chosen scratch baseline and permanent
    predecessor are restored exactly; the baseline itself need not have empty
    history. -/
theorem recordedSegmentStage_apply_of_run
    {Alpha Record : Type*} {step : PartialStep Alpha}
    [DecidableEq Alpha] [DecidableEq Record]
    (recorder : HistoryRecorder step Record)
    (blankScratch : HistoryState Alpha Record) (blankDump : Alpha)
    {length : Nat} {before after : Alpha}
    (hrun : step.Runs length before after) :
    recordedSegmentStage recorder blankScratch blankDump length
        ((before, blankScratch), blankDump) =
      some ((before, blankScratch), after) := by
  obtain ⟨generatedHistory, hrecorded⟩ :=
    (recorder.exists_forward_run_iff length before after []).mp hrun
  let terminal : HistoryState Alpha Record :=
    ⟨after, generatedHistory⟩
  have hsegment :
      recordedEquivAt recorder length
          (⟨before, []⟩ : HistoryState Alpha Record) =
        some terminal := by
    simpa [terminal, PartialStep.Runs] using hrecorded
  simpa [recordedSegmentStage, terminal] using
    (stage_apply_of_segment
      (fun checkpoint : Alpha =>
        (⟨checkpoint, []⟩ : HistoryState Alpha Record))
      (fun state : HistoryState Alpha Record => state.current)
      blankScratch blankDump (recordedEquivAt recorder length)
      before terminal hsegment)

/-- The inverse validates the terminal checkpoint and deletes it, again
    leaving no segment-generated primary history in scratch. -/
theorem recordedSegmentStage_symm_cleanup_of_run
    {Alpha Record : Type*} {step : PartialStep Alpha}
    [DecidableEq Alpha] [DecidableEq Record]
    (recorder : HistoryRecorder step Record)
    (blankScratch : HistoryState Alpha Record) (blankDump : Alpha)
    {length : Nat} {before after : Alpha}
    (hrun : step.Runs length before after) :
    (recordedSegmentStage recorder blankScratch blankDump length).symm
        ((before, blankScratch), after) =
      some ((before, blankScratch), blankDump) := by
  apply (recordedSegmentStage recorder blankScratch blankDump length).eq_some_iff.mpr
  exact recordedSegmentStage_apply_of_run
    recorder blankScratch blankDump hrun

/-! ## Global finite checkpoint program -/

/--
State of a segmented computation.

The original field is permanent. The current field is the current restart
state. Intermediate dumps store earlier restart states newest-first. The type
`α` denotes a *complete* restart checkpoint, including every machine component
needed to resume a segment (for example control state, tapes, and head
positions), rather than merely an output value. Completed counts successfully
completed segments.
-/
structure ChainState (α : Type*) where
  original : α
  current : α
  completed : Nat
  intermediateDumps : List α
deriving DecidableEq, Repr

/-- Canonical state before any segment: no duplicate dump of the input. -/
def ChainState.initial (input : α) : ChainState α :=
  { original := input
    current := input
    completed := 0
    intermediateDumps := [] }

/-- State update after a successful segment. The first segment needs no dump:
    its predecessor is already retained by the permanent original input. -/
def ChainState.recordNext (state : ChainState α) (next : α) : ChainState α :=
  match state.completed with
  | 0 =>
      { state with current := next, completed := 1 }
  | completed + 1 =>
      { state with
        current := next
        completed := completed + 2
        intermediateDumps := state.current :: state.intermediateDumps }

@[simp] theorem ChainState.recordNext_original
    (state : ChainState α) (next : α) :
    (state.recordNext next).original = state.original := by
  rcases state with ⟨original, current, completed, dumps⟩
  cases completed <;> rfl

@[simp] theorem ChainState.recordNext_current
    (state : ChainState α) (next : α) :
    (state.recordNext next).current = next := by
  rcases state with ⟨original, current, completed, dumps⟩
  cases completed <;> rfl

@[simp] theorem ChainState.recordNext_completed
    (state : ChainState α) (next : α) :
    (state.recordNext next).completed = state.completed + 1 := by
  rcases state with ⟨original, current, completed, dumps⟩
  cases completed <;> simp [ChainState.recordNext]

/-- A boundary state contains exactly the restart dumps forced by its index.
    At index zero its live restart state must still be the permanent input. -/
def ChainState.WellFormed (state : ChainState α) : Prop :=
  (state.completed = 0 → state.current = state.original) ∧
    state.intermediateDumps.length = state.completed - 1

@[simp] theorem ChainState.initial_wellFormed (input : α) :
    (ChainState.initial input).WellFormed := by
  simp [ChainState.WellFormed, ChainState.initial]

/-- Recording one endpoint preserves the exact checkpoint-count invariant. -/
theorem ChainState.recordNext_wellFormed
    {state : ChainState α} (hstate : state.WellFormed) (next : α) :
    (state.recordNext next).WellFormed := by
  rcases state with ⟨original, current, completed, dumps⟩
  cases completed with
  | zero =>
      change (0 = 0 → current = original) ∧
        dumps.length = 0 - 1 at hstate
      change (1 = 0 → next = original) ∧
        dumps.length = 1 - 1
      constructor
      · omega
      · simpa using hstate.2
  | succ completed =>
      simp only [ChainState.WellFormed, ChainState.recordNext,
        List.length_cons] at hstate ⊢
      constructor
      · omega
      · omega

/-- Execute the segment indexed by completed, retaining its predecessor when
    it is not already the permanent original input. -/
def forward [DecidableEq α] (segments : List (PartialStep α)) :
    PartialStep (ChainState α)
  | state =>
      match segments[state.completed]? with
      | none => none
      | some segment =>
          match state.completed with
          | 0 =>
              if state.current = state.original then
                (segment state.current).map state.recordNext
              else none
          | _ + 1 =>
              (segment state.current).map state.recordNext

/-- A successful global step is exactly a successful indexed segment followed
    by `recordNext`. -/
theorem forward_eq_some_iff [DecidableEq α]
    (segments : List (PartialStep α)) (before after : ChainState α) :
    forward segments before = some after ↔
      (before.completed = 0 → before.current = before.original) ∧
        ∃ segment next,
          segments[before.completed]? = some segment ∧
          segment before.current = some next ∧
          after = before.recordNext next := by
  rcases before with ⟨original, current, completed, dumps⟩
  cases completed with
  | zero =>
      by_cases hcurrent : current = original
      · subst current
        cases hsegment : segments[0]? with
        | none => simp [forward, hsegment]
        | some segment =>
            cases hnext : segment original with
            | none => simp [forward, hsegment, hnext]
            | some next =>
                simp [forward, hsegment, hnext, ChainState.recordNext, eq_comm]
      · constructor
        · intro hforward
          cases hsegment : segments[0]? <;>
            simp [forward, hcurrent, hsegment] at hforward
        · rintro ⟨hvalid, segment, next, hsegment, hnext, hafter⟩
          exact (hcurrent (hvalid rfl)).elim
  | succ completed =>
      cases hsegment : segments[completed + 1]? with
      | none => simp [forward, hsegment]
      | some segment =>
          cases hnext : segment current with
          | none => simp [forward, hsegment, hnext]
          | some next =>
              simp [forward, hsegment, hnext, ChainState.recordNext, eq_comm]

/-- One successful segment preserves the permanent original input. -/
theorem forward_original [DecidableEq α]
    (segments : List (PartialStep α)) {before after : ChainState α}
    (hforward : forward segments before = some after) :
    after.original = before.original := by
  obtain ⟨hvalid, segment, next, hsegment, hnext, rfl⟩ :=
    (forward_eq_some_iff segments before after).mp hforward
  exact ChainState.recordNext_original before next

/-- One successful segment increments the completed-segment index exactly. -/
theorem forward_completed [DecidableEq α]
    (segments : List (PartialStep α)) {before after : ChainState α}
    (hforward : forward segments before = some after) :
    after.completed = before.completed + 1 := by
  obtain ⟨hvalid, segment, next, hsegment, hnext, rfl⟩ :=
    (forward_eq_some_iff segments before after).mp hforward
  exact ChainState.recordNext_completed before next

/-- A successful segment preserves the boundary-state invariant. -/
theorem forward_wellFormed [DecidableEq α]
    (segments : List (PartialStep α)) {before after : ChainState α}
    (hbefore : before.WellFormed)
    (hforward : forward segments before = some after) :
    after.WellFormed := by
  obtain ⟨hvalid, segment, next, hsegment, hnext, rfl⟩ :=
    (forward_eq_some_iff segments before after).mp hforward
  exact ChainState.recordNext_wellFormed hbefore next

/-- Verify one segment and remove exactly the checkpoint introduced by it. -/
def backward [DecidableEq α] (segments : List (PartialStep α)) :
    PartialStep (ChainState α)
  | state =>
      match state.completed with
      | 0 => none
      | 1 =>
          match segments[0]? with
          | none => none
          | some segment =>
              if segment state.original = some state.current then
                some
                  { state with
                    current := state.original
                    completed := 0 }
              else none
      | completed + 2 =>
          match state.intermediateDumps with
          | [] => none
          | previous :: dumps =>
              match segments[completed + 1]? with
              | none => none
              | some segment =>
                  if segment previous = some state.current then
                    some
                      { state with
                        current := previous
                        completed := completed + 1
                        intermediateDumps := dumps }
                  else none

/-- Every successful forward segment is accepted by inverse cleanup. -/
theorem backward_of_forward_eq [DecidableEq α]
    (segments : List (PartialStep α)) {before after : ChainState α}
    (hforward : forward segments before = some after) :
    backward segments after = some before := by
  rcases before with ⟨original, current, completed, dumps⟩
  cases completed with
  | zero =>
      by_cases hcurrent : current = original
      · subst current
        cases hsegment : segments[0]? with
        | none => simp [forward, hsegment] at hforward
        | some segment =>
            cases hnext : segment original with
            | none => simp [forward, hsegment, hnext] at hforward
            | some next =>
                have hafter : after =
                    ⟨original, next, 1, dumps⟩ := by
                  simpa [forward, hsegment, hnext,
                    ChainState.recordNext] using hforward.symm
                subst after
                simp [backward, hsegment, hnext]
      · cases hsegment : segments[0]? <;>
          simp [forward, hcurrent, hsegment] at hforward
  | succ completed =>
      cases hsegment : segments[completed + 1]? with
      | none => simp [forward, hsegment] at hforward
      | some segment =>
          cases hnext : segment current with
          | none => simp [forward, hsegment, hnext] at hforward
          | some next =>
              have hafter : after =
                  ⟨original, next, completed + 2, current :: dumps⟩ := by
                simpa [forward, hsegment, hnext,
                  ChainState.recordNext] using hforward.symm
              subst after
              simp [backward, hsegment, hnext]

/-- Every accepted cleanup step is reproduced by the forward transition. -/
theorem forward_of_backward_eq [DecidableEq α]
    (segments : List (PartialStep α)) {after before : ChainState α}
    (hbackward : backward segments after = some before) :
    forward segments before = some after := by
  rcases after with ⟨original, current, completed, dumps⟩
  cases completed with
  | zero => simp [backward] at hbackward
  | succ completed =>
      cases completed with
      | zero =>
          cases hsegment : segments[0]? with
          | none => simp [backward, hsegment] at hbackward
          | some segment =>
              by_cases hnext : segment original = some current
              · have hbefore : before = ⟨original, original, 0, dumps⟩ := by
                  simpa [backward, hsegment, hnext] using hbackward.symm
                subst before
                simp [forward, hsegment, hnext, ChainState.recordNext]
              · simp [backward, hsegment, hnext] at hbackward
      | succ previousCompleted =>
          cases dumps with
          | nil => simp [backward] at hbackward
          | cons previous dumps =>
              cases hsegment : segments[previousCompleted + 1]? with
              | none => simp [backward, hsegment] at hbackward
              | some segment =>
                  by_cases hnext : segment previous = some current
                  · have hbefore : before =
                        ⟨original, previous, previousCompleted + 1, dumps⟩ := by
                      simpa [backward, hsegment, hnext] using hbackward.symm
                    subst before
                    simp [forward, hsegment, hnext,
                      ChainState.recordNext]
                  · simp [backward, hsegment, hnext] at hbackward

/-- Forward and backward checkpoint transitions have converse graphs globally. -/
theorem areInverses [DecidableEq α]
    (segments : List (PartialStep α)) :
    (forward segments).AreInverses (backward segments) := by
  intro before after
  exact ⟨backward_of_forward_eq segments, forward_of_backward_eq segments⟩

/-- Forward and backward checkpoint transitions form a global partial equivalence. -/
def equiv [DecidableEq α] (segments : List (PartialStep α)) :
    ChainState α ≃. ChainState α :=
  (areInverses segments).toInversePair

/-- The packaged transition exposes the declared forward checkpoint step. -/
@[simp] theorem equiv_apply [DecidableEq α]
    (segments : List (PartialStep α)) (state : ChainState α) :
    equiv segments state = forward segments state :=
  rfl

/-- The packaged inverse exposes the validating checkpoint cleanup step. -/
@[simp] theorem equiv_symm_apply [DecidableEq α]
    (segments : List (PartialStep α)) (state : ChainState α) :
    (equiv segments).symm state = backward segments state :=
  rfl

/-- Every finite checkpoint execution cleans up by the same number of inverse steps. -/
theorem inverse_cleanup [DecidableEq α]
    (segments : List (PartialStep α)) {n : Nat}
    {before after : ChainState α}
    (hrun : (forward segments).Runs n before after) :
    (backward segments).Runs n after before :=
  ((areInverses segments).runs_iff n before after).mp hrun

/-! ## Exact finite-run accounting -/

/-- A finite checkpoint run never changes the permanent original input. -/
theorem original_eq_of_runs [DecidableEq α]
    (segments : List (PartialStep α)) {n : Nat}
    {before after : ChainState α}
    (hrun : (forward segments).Runs n before after) :
    after.original = before.original := by
  induction n generalizing before after with
  | zero =>
      have hbefore : before = after :=
        (PartialStep.runs_zero_iff (forward segments) before after).mp hrun
      subst after
      rfl
  | succ n ih =>
      obtain ⟨middle, hfirst, htail⟩ :=
        (PartialStep.runs_succ_iff (forward segments) n before after).mp hrun
      exact (ih htail).trans (forward_original segments hfirst)

/-- The boundary index after `n` successful segments is the starting index
    plus `n`; this is independent of the segment implementations. -/
theorem completed_eq_add_of_runs [DecidableEq α]
    (segments : List (PartialStep α)) {n : Nat}
    {before after : ChainState α}
    (hrun : (forward segments).Runs n before after) :
    after.completed = before.completed + n := by
  induction n generalizing before after with
  | zero =>
      have hbefore : before = after :=
        (PartialStep.runs_zero_iff (forward segments) before after).mp hrun
      subst after
      simp
  | succ n ih =>
      obtain ⟨middle, hfirst, htail⟩ :=
        (PartialStep.runs_succ_iff (forward segments) n before after).mp hrun
      have htailIndex := ih htail
      have hfirstIndex := forward_completed segments hfirst
      omega

/-- The exact restart-dump invariant is preserved by every finite run. -/
theorem wellFormed_of_runs [DecidableEq α]
    (segments : List (PartialStep α)) {n : Nat}
    {before after : ChainState α} (hbefore : before.WellFormed)
    (hrun : (forward segments).Runs n before after) :
    after.WellFormed := by
  induction n generalizing before after with
  | zero =>
      have hsame : before = after :=
        (PartialStep.runs_zero_iff (forward segments) before after).mp hrun
      simpa [hsame] using hbefore
  | succ n ih =>
      obtain ⟨middle, hfirst, htail⟩ :=
        (PartialStep.runs_succ_iff (forward segments) n before after).mp hrun
      exact ih (forward_wellFormed segments hbefore hfirst) htail

/-- Canonical execution of `n` declared segments has completed index `n`,
    keeps the original input, and stores exactly `n - 1` restart dumps. -/
theorem run_from_initial_shape [DecidableEq α]
    (segments : List (PartialStep α)) {n : Nat} {input : α}
    {after : ChainState α}
    (hrun : (forward segments).Runs n (ChainState.initial input) after) :
    after.original = input ∧
      after.completed = n ∧
      after.intermediateDumps.length = n - 1 := by
  have horiginal := original_eq_of_runs segments hrun
  have hcompleted := completed_eq_add_of_runs segments hrun
  have hwellFormed := wellFormed_of_runs segments
    (ChainState.initial_wellFormed input) hrun
  refine ⟨?_, ?_, ?_⟩
  · simpa [ChainState.initial] using horiginal
  · simpa [ChainState.initial] using hcompleted
  · rw [hwellFormed.2]
    have hcompleted' : after.completed = n := by
      simpa [ChainState.initial] using hcompleted
    omega

/-- Completing the full declared list means executing exactly its length. -/
def Completes [DecidableEq α] (segments : List (PartialStep α))
    (input : α) (terminal : ChainState α) : Prop :=
  (forward segments).Runs segments.length (ChainState.initial input) terminal

/-- A full finite segment list leaves one fewer intermediate restart dump than
    the number of segments; the permanent input supplies the missing first
    predecessor checkpoint. -/
theorem dump_count_of_completes [DecidableEq α]
    (segments : List (PartialStep α)) {input : α}
    {terminal : ChainState α}
    (hcomplete : Completes segments input terminal) :
    terminal.intermediateDumps.length = segments.length - 1 :=
  (run_from_initial_shape segments hcomplete).2.2

/-- Full-list completion is followed by list-exhaustion halting. -/
theorem halted_of_completes [DecidableEq α]
    (segments : List (PartialStep α)) {input : α}
    {terminal : ChainState α}
    (hcomplete : Completes segments input terminal) :
    (forward segments).Halted terminal := by
  have hcompleted := (run_from_initial_shape segments hcomplete).2.1
  rcases terminal with ⟨original, current, completed, dumps⟩
  simp only at hcompleted
  subst completed
  simp [PartialStep.Halted, forward]

/-- Reversing a full-list execution removes every higher-level restart dump
    and returns to the canonical boundary state. -/
theorem cleanup_of_completes [DecidableEq α]
    (segments : List (PartialStep α)) {input : α}
    {terminal : ChainState α}
    (hcomplete : Completes segments input terminal) :
    (backward segments).Runs segments.length terminal
      (ChainState.initial input) :=
  inverse_cleanup segments hcomplete

/-- Once the boundary index reaches the list length there is no further
    declared segment. This is list exhaustion, not a source-machine halt test. -/
theorem forward_halted_at_end [DecidableEq α]
    (segments : List (PartialStep α)) (state : ChainState α)
    (hcompleted : state.completed = segments.length) :
    forward segments state = none := by
  rcases state with ⟨original, current, completed, dumps⟩
  simp only at hcompleted
  subst completed
  simp [forward]

/-! ## Exact-length composition and checkpoint cleanup -/

/-- Package exactly `n` checkpoint segments and their reverse cleanup as one
    partial equivalence. -/
def equivAt [DecidableEq α] (segments : List (PartialStep α)) (n : Nat) :
    ChainState α ≃. ChainState α :=
  ((areInverses segments).iterate n).toInversePair

@[simp] theorem equivAt_apply [DecidableEq α]
    (segments : List (PartialStep α)) (n : Nat) (state : ChainState α) :
    equivAt segments n state = (forward segments).iterate n state :=
  rfl

@[simp] theorem equivAt_symm_apply [DecidableEq α]
    (segments : List (PartialStep α)) (n : Nat) (state : ChainState α) :
    (equivAt segments n).symm state = (backward segments).iterate n state :=
  rfl

/-- Exact-length compute-copy-cleanup for checkpoint chains. There is no halt
    guard: success means precisely that the requested segment prefix exists
    and that the output register initially contains `blank`. -/
def computeCopyCleanup [DecidableEq α] [DecidableEq β]
    (segments : List (PartialStep α)) (observe : α → β)
    (blank : β) (n : Nat) :
    (ChainState α × β) ≃. (ChainState α × β) :=
  let compute := liftRight (equivAt segments n) β
  let copyOutput :=
    Bennett.Copy.observedEquiv (fun state : ChainState α =>
      observe state.current) blank
  (compute.trans copyOutput).trans compute.symm

/-- The exact-length macro restores every checkpoint field, including the
    current restart state and dump stack, while retaining the copied result. -/
theorem computeCopyCleanup_apply_of_run
    [DecidableEq α] [DecidableEq β]
    (segments : List (PartialStep α)) (observe : α → β)
    (blank : β) {n : Nat} {before after : ChainState α}
    (hrun : (forward segments).Runs n before after) :
    computeCopyCleanup segments observe blank n (before, blank) =
      some (before, observe after.current) := by
  have hback : (backward segments).Runs n after before :=
    inverse_cleanup segments hrun
  change (forward segments).iterate n before = some after at hrun
  change (backward segments).iterate n after = some before at hback
  change
    ((((forward segments).iterate n before).map
        (fun computed => (computed, blank))).bind
      (Bennett.Copy.observedForward
        (fun state : ChainState α => observe state.current) blank)).bind
      (fun copied =>
        ((backward segments).iterate n copied.1).map
          (fun restored => (restored, copied.2))) = _
  simp [hrun, hback, Bennett.Copy.observedForward]

/-- The inverse verifies the copied observation, blanks the output register,
    and restores the same checkpoint-chain state. -/
theorem computeCopyCleanup_symm_apply_of_run
    [DecidableEq α] [DecidableEq β]
    (segments : List (PartialStep α)) (observe : α → β)
    (blank : β) {n : Nat} {before after : ChainState α}
    (hrun : (forward segments).Runs n before after) :
    (computeCopyCleanup segments observe blank n).symm
        (before, observe after.current) = some (before, blank) := by
  apply (computeCopyCleanup segments observe blank n).eq_some_iff.mpr
  exact computeCopyCleanup_apply_of_run segments observe blank hrun

/-- Full-list compute-copy-cleanup begins and ends with the canonical state:
    the input is retained and all temporary restart dumps are erased. -/
theorem computeCopyCleanup_initial_of_completes
    [DecidableEq α] [DecidableEq β]
    (segments : List (PartialStep α)) (observe : α → β)
    (blank : β) {input : α} {terminal : ChainState α}
    (hcomplete : Completes segments input terminal) :
    computeCopyCleanup segments observe blank segments.length
        (ChainState.initial input, blank) =
      some (ChainState.initial input, observe terminal.current) :=
  computeCopyCleanup_apply_of_run segments observe blank hcomplete

/-- The packaged exact-length macro is globally logically reversible on its
    full partial domain. -/
theorem computeCopyCleanup_reversible
    [DecidableEq α] [DecidableEq β]
    (segments : List (PartialStep α)) (observe : α → β)
    (blank : β) (n : Nat) :
    PartialStep.Reversible
      (computeCopyCleanup segments observe blank n).toFun :=
  PartialStep.InversePair.forward_reversible _

end Bennett.Checkpoint
