import Bennett.Turing.Resource
import Bennett.Turing.Simulator.Copy
import Bennett.Turing.Simulator.Reverse
import Lean.Elab.Tactic.Omega

/-!
# Resource accounting for the three-tape simulator

This module turns an explicit quadruple schedule into a concrete nonempty
state trace.  It then gives exact transition, state, and scanned-cell counts
for Table 1's copy sweep.  The trace constructor executes the displayed rules
without asserting that they match; semantic applications can pair it with
`Quadruple.Scheduled`, such as `Copy.scheduled`.
-/

namespace Bennett.Turing
namespace Quadruple

variable {Control TapeIndex : Type*} {Symbol : TapeIndex → Type*}

/-- States obtained after each rule of a displayed schedule. -/
def executeTail :
    List (Quadruple Control TapeIndex Symbol) →
      MultiConfiguration Control TapeIndex Symbol →
      List (MultiConfiguration Control TapeIndex Symbol)
  | [], _ => []
  | rule :: rules, before =>
      let after := rule.execute before
      after :: executeTail rules after

/-- The concrete nonempty trace generated by a displayed schedule. -/
def executionTrace (rules : List (Quadruple Control TapeIndex Symbol))
    (start : MultiConfiguration Control TapeIndex Symbol) :
    ExecutionTrace (MultiConfiguration Control TapeIndex Symbol) :=
  ⟨start, executeTail rules start⟩

@[simp] theorem executionTrace_states_nil
    (start : MultiConfiguration Control TapeIndex Symbol) :
    (executionTrace [] start).states = [start] := rfl

@[simp] theorem executionTrace_states_cons
    (rule : Quadruple Control TapeIndex Symbol)
    (rules : List (Quadruple Control TapeIndex Symbol))
    (start : MultiConfiguration Control TapeIndex Symbol) :
    (executionTrace (rule :: rules) start).states =
      start :: (executionTrace rules (rule.execute start)).states := rfl

@[simp] theorem executionTrace_transitionCount
    (rules : List (Quadruple Control TapeIndex Symbol))
    (start : MultiConfiguration Control TapeIndex Symbol) :
    (executionTrace rules start).transitionCount = rules.length := by
  change (executeTail rules start).length = rules.length
  induction rules generalizing start with
  | nil => rfl
  | cons rule rules ih => simp [executeTail, ih]

@[simp] theorem executionTrace_stateCount
    (rules : List (Quadruple Control TapeIndex Symbol))
    (start : MultiConfiguration Control TapeIndex Symbol) :
    (executionTrace rules start).states.length = rules.length + 1 := by
  rw [ExecutionTrace.states_length, executionTrace_transitionCount]

/-- A tape projection of an explicit trace depends only on its initial tape. -/
theorem executionTrace_tapes_eq (index : TapeIndex)
    (rules : List (Quadruple Control TapeIndex Symbol))
    (first second : MultiConfiguration Control TapeIndex Symbol)
    (hinitial : first.tape index = second.tape index) :
    (executionTrace rules first).states.map (fun state => state.tape index) =
      (executionTrace rules second).states.map
        (fun state => state.tape index) := by
  induction rules generalizing first second with
  | nil => simp [hinitial]
  | cons rule rules ih =>
      simp only [executionTrace_states_cons, List.map_cons]
      congr 1
      apply ih
      simpa only [execute_tape] using
        congrArg ((rule.action index).execute) hinitial

/-- A step invariant holds at every state of a matching explicit schedule. -/
theorem Scheduled.forall_executionTrace
    {rules : List (Quadruple Control TapeIndex Symbol)}
    {start finish : MultiConfiguration Control TapeIndex Symbol}
    {predicate : MultiConfiguration Control TapeIndex Symbol → Prop}
    (hscheduled : Scheduled rules start finish)
    (hinitial : predicate start)
    (hstep : ∀ (rule : Quadruple Control TapeIndex Symbol)
      (before : MultiConfiguration Control TapeIndex Symbol),
      rule ∈ rules → rule.Matches before → predicate before →
        predicate (rule.execute before)) :
    ∀ state ∈ (executionTrace rules start).states, predicate state := by
  induction rules generalizing start with
  | nil =>
      intro state hstate
      have hstateEq : state = start := by simpa using hstate
      subst state
      exact hinitial
  | cons rule rules ih =>
      simp only [Scheduled] at hscheduled
      intro state hstate
      rw [executionTrace_states_cons] at hstate
      rcases List.mem_cons.mp hstate with rfl | htail
      · exact hinitial
      · apply ih hscheduled.2
          (hstep rule start (by simp) hscheduled.1 hinitial)
        · intro tailRule before hmem
          exact hstep tailRule before (by simp [hmem])
        · exact htail

end Quadruple

namespace Simulator.Copy.Resource

open Copy TapeInvariant

variable {SourceControl Symbol : Type}

/-- Common work/output head displacement of one copy rule. -/
def headOffset : CopyRuleId Symbol → Int
  | .moveRight => 1
  | .moveLeft => -1
  | _ => 0

/-- Head positions of all states in a constructor-tagged copy schedule. -/
def headWalk : Int → List (CopyRuleId Symbol) → List Int
  | position, [] => [position]
  | position, ruleId :: rules =>
      position :: headWalk (position + headOffset ruleId) rules

/-- Final head position after all displayed copy-rule tags. -/
def finalHead : Int → List (CopyRuleId Symbol) → Int
  | position, [] => position
  | position, ruleId :: rules =>
      finalHead (position + headOffset ruleId) rules

/-- Distinct positions scanned by the abstract copy head walk. -/
def headPositions (position : Int) (rules : List (CopyRuleId Symbol)) :
    Finset Int :=
  (headWalk position rules).toFinset

@[simp] theorem headWalk_nil (position : Int) :
    headWalk (Symbol := Symbol) position [] = [position] := rfl

@[simp] theorem headWalk_cons (position : Int) (ruleId : CopyRuleId Symbol)
    (rules : List (CopyRuleId Symbol)) :
    headWalk position (ruleId :: rules) =
      position :: headWalk (position + headOffset ruleId) rules := rfl

@[simp] theorem finalHead_nil (position : Int) :
    finalHead (Symbol := Symbol) position [] = position := rfl

@[simp] theorem finalHead_cons (position : Int) (ruleId : CopyRuleId Symbol)
    (rules : List (CopyRuleId Symbol)) :
    finalHead position (ruleId :: rules) =
      finalHead (position + headOffset ruleId) rules := rfl

@[simp] theorem headPositions_nil (position : Int) :
    headPositions (Symbol := Symbol) position [] = {position} := by
  simp [headPositions]

@[simp] theorem headPositions_cons (position : Int)
    (ruleId : CopyRuleId Symbol) (rules : List (CopyRuleId Symbol)) :
    headPositions position (ruleId :: rules) =
      insert position (headPositions (position + headOffset ruleId) rules) := by
  simp [headPositions]

theorem start_mem_headPositions (position : Int)
    (rules : List (CopyRuleId Symbol)) :
    position ∈ headPositions position rules := by
  cases rules <;> simp

theorem headWalk_append (position : Int)
    (first second : List (CopyRuleId Symbol)) :
    headWalk position (first ++ second) =
      (headWalk position first).dropLast ++
        headWalk (finalHead position first) second := by
  induction first generalizing position with
  | nil => simp
  | cons ruleId rules ih =>
      simp only [List.cons_append, headWalk_cons, finalHead_cons]
      rw [ih]
      have hnonempty :
          headWalk (position + headOffset ruleId) rules ≠ [] := by
        cases rules <;> simp
      rw [List.dropLast_cons_of_ne_nil hnonempty]
      simp only [List.cons_append]

theorem finalHead_append (position : Int)
    (first second : List (CopyRuleId Symbol)) :
    finalHead position (first ++ second) =
      finalHead (finalHead position first) second := by
  induction first generalizing position with
  | nil => rfl
  | cons ruleId rules ih => simp [ih]

theorem headPositions_append (position : Int)
    (first second : List (CopyRuleId Symbol)) :
    headPositions position (first ++ second) =
      headPositions position first ∪
        headPositions (finalHead position first) second := by
  induction first generalizing position with
  | nil =>
      ext candidate
      simp [start_mem_headPositions]
  | cons ruleId rules ih =>
      simp only [List.cons_append, headPositions_cons, finalHead_cons,
        ih, Finset.insert_union]

@[simp] theorem finalHead_forwardIds (position : Int) (word : List Symbol) :
    finalHead position (forwardIds word) =
      position + (word.length : Int) := by
  induction word generalizing position with
  | nil => simp [forwardIds]
  | cons symbol suffix ih =>
      simp [forwardIds, headOffset, ih]
      omega

@[simp] theorem finalHead_backwardIds (position : Int) (word : List Symbol) :
    finalHead position (backwardIds word) =
      position - (word.length : Int) := by
  induction word generalizing position with
  | nil => simp [backwardIds]
  | cons symbol suffix ih =>
      simp [backwardIds, headOffset, ih]
      omega

theorem headPositions_forwardIds (position : Int) (word : List Symbol) :
    headPositions position (forwardIds word) =
      Finset.Icc position (position + (word.length : Int)) := by
  induction word generalizing position with
  | nil => simp [forwardIds]
  | cons symbol suffix ih =>
      simp only [forwardIds, headPositions_cons, headOffset, ih,
        List.length_cons, Int.natCast_succ]
      ext candidate
      simp only [Finset.mem_insert, Finset.mem_Icc]
      omega

theorem headPositions_backwardIds (position : Int) (word : List Symbol) :
    headPositions position (backwardIds word) =
      Finset.Icc (position - (word.length : Int)) position := by
  induction word generalizing position with
  | nil => simp [backwardIds]
  | cons symbol suffix ih =>
      simp only [backwardIds, headPositions_cons, headOffset, ih,
        List.length_cons, Int.natCast_succ]
      ext candidate
      simp only [Finset.mem_insert, Finset.mem_Icc]
      omega

/-- Exact distinct head positions of Table 1's complete copy rule-ID list. -/
theorem headPositions_ids (word : List Symbol) :
    headPositions (-1) (ids word) = Tape.delimiterTraversal word := by
  simp only [ids, headPositions_append, finalHead_append,
    headPositions_cons, headPositions_nil, finalHead_cons, finalHead_nil,
    headOffset, headPositions_forwardIds, finalHead_forwardIds,
    headPositions_backwardIds, finalHead_backwardIds,
    List.length_reverse, Tape.delimiterTraversal]
  ext candidate
  simp only [Finset.mem_union, Finset.mem_insert, Finset.mem_singleton,
    Finset.mem_Icc]
  omega

@[simp] theorem headPositions_ids_card (word : List Symbol) :
    (headPositions (-1) (ids word)).card = word.length + 2 := by
  rw [headPositions_ids]
  exact Tape.delimiterTraversal_card word

theorem execute_work_head {source : Machine SourceControl Symbol}
    (finish : SourceControl) (terminal : source.RuleId)
    (ruleId : CopyRuleId Symbol) (before : Simulator.Configuration source) :
    (((ruleAt source finish terminal ruleId).execute before).tape .work).head =
      (before.tape .work).head + headOffset ruleId := by
  cases ruleId <;> simp [ruleAt, threeRule, headOffset,
    Quadruple.execute_tape, Action.execute]

theorem execute_output_head {source : Machine SourceControl Symbol}
    (finish : SourceControl) (terminal : source.RuleId)
    (ruleId : CopyRuleId Symbol) (before : Simulator.Configuration source) :
    (((ruleAt source finish terminal ruleId).execute before).tape .output).head =
      (before.tape .output).head + headOffset ruleId := by
  cases ruleId <;> simp [ruleAt, threeRule, headOffset,
    Quadruple.execute_tape, Action.execute]

theorem execute_history_head {source : Machine SourceControl Symbol}
    (finish : SourceControl) (terminal : source.RuleId)
    (ruleId : CopyRuleId Symbol) (before : Simulator.Configuration source) :
    (((ruleAt source finish terminal ruleId).execute before).tape .history).head =
      (before.tape .history).head := by
  cases ruleId <;> simp [ruleAt, threeRule, Quadruple.execute_tape,
    Action.execute]

theorem trace_work_heads {source : Machine SourceControl Symbol}
    (finish : SourceControl) (terminal : source.RuleId)
    (ruleIds : List (CopyRuleId Symbol))
    (start : Simulator.Configuration source) :
    ((Quadruple.executionTrace
        (ruleIds.map (ruleAt source finish terminal)) start).states.map
      (fun state => (state.tape .work).head)) =
      headWalk (start.tape .work).head ruleIds := by
  induction ruleIds generalizing start with
  | nil => rfl
  | cons ruleId ruleIds ih =>
      simp only [List.map_cons, Quadruple.executionTrace_states_cons,
        List.map_cons, headWalk_cons]
      congr 1
      rw [ih, execute_work_head]

theorem trace_output_heads {source : Machine SourceControl Symbol}
    (finish : SourceControl) (terminal : source.RuleId)
    (ruleIds : List (CopyRuleId Symbol))
    (start : Simulator.Configuration source) :
    ((Quadruple.executionTrace
        (ruleIds.map (ruleAt source finish terminal)) start).states.map
      (fun state => (state.tape .output).head)) =
      headWalk (start.tape .output).head ruleIds := by
  induction ruleIds generalizing start with
  | nil => rfl
  | cons ruleId ruleIds ih =>
      simp only [List.map_cons, Quadruple.executionTrace_states_cons,
        List.map_cons, headWalk_cons]
      congr 1
      rw [ih, execute_output_head]

theorem trace_history_heads {source : Machine SourceControl Symbol}
    (finish : SourceControl) (terminal : source.RuleId)
    (ruleIds : List (CopyRuleId Symbol))
    (start : Simulator.Configuration source) :
    ((Quadruple.executionTrace
        (ruleIds.map (ruleAt source finish terminal)) start).states.map
      (fun state => (state.tape .history).head)) =
      List.replicate (ruleIds.length + 1) (start.tape .history).head := by
  induction ruleIds generalizing start with
  | nil => rfl
  | cons ruleId ruleIds ih =>
      simp only [List.map_cons, Quadruple.executionTrace_states_cons,
        List.map_cons, List.length_cons]
      rw [ih, execute_history_head]
      rw [show ruleIds.length + 1 = Nat.succ ruleIds.length by omega,
        List.replicate_succ]
      rfl

/-- Cell/support invariant needed for exact copy-space accounting. -/
structure DataInvariant {source : Machine SourceControl Symbol}
    (word : List Symbol) (state : Simulator.Configuration source) : Prop where
  workCells : (state.tape .work).cells = (Tape.ofWord word).cells
  dataHeads : (state.tape .work).head = (state.tape .output).head
  outputSupport : (state.tape .output).nonblankPositions ⊆
    (Tape.ofWord word).nonblankPositions

variable [DecidableEq SourceControl] [DecidableEq Symbol]

theorem execute_work_cells_of_matches
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source)
    (ruleId : CopyRuleId Symbol) (before : Simulator.Configuration source)
    (hmatch : (rule normal ruleId).Matches before) :
    (((rule normal ruleId).execute before).tape .work).cells =
      (before.tape .work).cells := by
  have hwork := hmatch.2 .work
  cases ruleId with
  | enter | turn | exit =>
      simp only [rule, ruleAt, threeRule, Action.Matches] at hwork
      simp only [rule, ruleAt, threeRule, Quadruple.execute_tape,
        Action.execute]
      rw [← hwork, Tape.write_read]
  | copySymbol symbol | checkSymbol symbol =>
      simp only [rule, ruleAt, threeRule, Action.Matches] at hwork
      simp only [rule, ruleAt, threeRule, Quadruple.execute_tape,
        Action.execute]
      rw [← hwork, Tape.write_read]
  | moveRight | moveLeft => rfl

theorem execute_dataHeads
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source)
    (ruleId : CopyRuleId Symbol) (before : Simulator.Configuration source)
    (hheads : (before.tape .work).head = (before.tape .output).head) :
    (((rule normal ruleId).execute before).tape .work).head =
      (((rule normal ruleId).execute before).tape .output).head := by
  cases ruleId <;>
    simp_all [rule, ruleAt, threeRule, Action.execute, Tape.move]

theorem work_head_mem_of_match
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source) (symbol : Symbol)
    (before : Simulator.Configuration source)
    (hmatch : (rule normal (.copySymbol symbol)).Matches before) :
    (before.tape .work).head ∈ (before.tape .work).nonblankPositions := by
  have hread := hmatch.2 .work
  simp only [rule, ruleAt, threeRule, Action.Matches] at hread
  rw [Tape.nonblankPositions, Finsupp.mem_support_iff]
  intro hblank
  have : (before.tape .work).read = .blank := by
    simpa [Tape.read] using hblank
  rw [this] at hread
  contradiction

theorem DataInvariant.execute
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source) (word : List Symbol)
    (ruleId : CopyRuleId Symbol) (before : Simulator.Configuration source)
    (hmatch : (rule normal ruleId).Matches before)
    (hinvariant : DataInvariant word before) :
    DataInvariant word ((rule normal ruleId).execute before) := by
  constructor
  · rw [execute_work_cells_of_matches normal ruleId before hmatch]
    exact hinvariant.workCells
  · exact execute_dataHeads normal ruleId before hinvariant.dataHeads
  · cases ruleId with
    | copySymbol symbol =>
        have hheadWork := work_head_mem_of_match normal symbol before hmatch
        have hheadWord :
            (before.tape .output).head ∈
              (Tape.ofWord word).nonblankPositions := by
          rw [← hinvariant.dataHeads]
          change (before.tape .work).head ∈ (Tape.ofWord word).cells.support
          rw [← hinvariant.workCells]
          exact hheadWork
        intro position hposition
        change position ∈ insert (before.tape .output).head
          (before.tape .output).nonblankPositions at hposition
        rw [Finset.mem_insert] at hposition
        rcases hposition with hposition | hposition
        · simpa [hposition] using hheadWord
        · exact hinvariant.outputSupport hposition
    | enter =>
        have houtput := hmatch.2 .output
        simp only [rule, ruleAt, threeRule, Action.Matches] at houtput
        change ((before.tape .output).write .blank).nonblankPositions ⊆ _
        have htape : (before.tape .output).write .blank =
            before.tape .output := by
          exact (congrArg (before.tape .output).write houtput.symm).trans
            (Tape.write_read (before.tape .output))
        rw [htape]
        exact hinvariant.outputSupport
    | turn =>
        have houtput := hmatch.2 .output
        simp only [rule, ruleAt, threeRule, Action.Matches] at houtput
        change ((before.tape .output).write .blank).nonblankPositions ⊆ _
        have htape : (before.tape .output).write .blank =
            before.tape .output := by
          exact (congrArg (before.tape .output).write houtput.symm).trans
            (Tape.write_read (before.tape .output))
        rw [htape]
        exact hinvariant.outputSupport
    | exit =>
        have houtput := hmatch.2 .output
        simp only [rule, ruleAt, threeRule, Action.Matches] at houtput
        change ((before.tape .output).write .blank).nonblankPositions ⊆ _
        have htape : (before.tape .output).write .blank =
            before.tape .output := by
          exact (congrArg (before.tape .output).write houtput.symm).trans
            (Tape.write_read (before.tape .output))
        rw [htape]
        exact hinvariant.outputSupport
    | checkSymbol symbol =>
        have houtput := hmatch.2 .output
        simp only [rule, ruleAt, threeRule, Action.Matches] at houtput
        change ((before.tape .output).write
          (.mark symbol)).nonblankPositions ⊆ _
        have htape : (before.tape .output).write (.mark symbol) =
            before.tape .output := by
          exact (congrArg (before.tape .output).write houtput.symm).trans
            (Tape.write_read (before.tape .output))
        rw [htape]
        exact hinvariant.outputSupport
    | moveRight =>
        change ((before.tape .output).move .right).nonblankPositions ⊆ _
        simpa [Tape.nonblankPositions] using hinvariant.outputSupport
    | moveLeft =>
        change ((before.tape .output).move .left).nonblankPositions ⊆ _
        simpa [Tape.nonblankPositions] using hinvariant.outputSupport

/-- The concrete trace generated by Table 1's copy schedule. -/
def copyTrace {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source)
    (history : Tape source.RuleId) (word : List Symbol) :
    ExecutionTrace (Simulator.Configuration source) :=
  Quadruple.executionTrace (schedule normal word)
    (configuration source (.forward normal.finish)
      (Tape.ofWord word) history (Tape.blankAt (-1)))

/-- Exact work-head sequence of the concrete copy trace. -/
theorem copyTrace_work_heads
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source)
    (history : Tape source.RuleId) (word : List Symbol) :
    (copyTrace normal history word).states.map
      (fun state => (state.tape .work).head) =
      headWalk (-1) (ids word) := by
  unfold copyTrace schedule rule
  rw [trace_work_heads]
  rfl

/-- Exact output-head sequence of the concrete copy trace. -/
theorem copyTrace_output_heads
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source)
    (history : Tape source.RuleId) (word : List Symbol) :
    (copyTrace normal history word).states.map
      (fun state => (state.tape .output).head) =
      headWalk (-1) (ids word) := by
  unfold copyTrace schedule rule
  rw [trace_output_heads]
  rfl

@[simp] theorem copyTrace_transitionCount
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source)
    (history : Tape source.RuleId) (word : List Symbol) :
    (copyTrace normal history word).transitionCount =
      4 * word.length + 5 := by
  simp [copyTrace, schedule]

@[simp] theorem copyTrace_stateCount
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source)
    (history : Tape source.RuleId) (word : List Symbol) :
    (copyTrace normal history word).states.length =
      4 * word.length + 6 := by
  rw [ExecutionTrace.states_length, copyTrace_transitionCount]

/-- Both data heads scan exactly the word cells and its two delimiters. -/
theorem copyTrace_work_visitedPositions
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source)
    (history : Tape source.RuleId) (word : List Symbol) :
    ExecutionTrace.visitedPositions
      (fun state : Simulator.Configuration source => state.tape .work)
      (copyTrace normal history word) =
      Tape.delimiterTraversal word := by
  unfold ExecutionTrace.visitedPositions copyTrace schedule rule
  rw [trace_work_heads]
  change headPositions (-1) (ids word) = Tape.delimiterTraversal word
  exact headPositions_ids word

theorem copyTrace_output_visitedPositions
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source)
    (history : Tape source.RuleId) (word : List Symbol) :
    ExecutionTrace.visitedPositions
      (fun state : Simulator.Configuration source => state.tape .output)
      (copyTrace normal history word) =
      Tape.delimiterTraversal word := by
  unfold ExecutionTrace.visitedPositions copyTrace schedule rule
  rw [trace_output_heads]
  change headPositions (-1) (ids word) = Tape.delimiterTraversal word
  exact headPositions_ids word

/-- The history head never moves during copying. -/
theorem copyTrace_history_heads
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source)
    (history : Tape source.RuleId) (word : List Symbol) :
    (copyTrace normal history word).states.map
      (fun state => (state.tape .history).head) =
      List.replicate (4 * word.length + 6) history.head := by
  unfold copyTrace schedule rule
  rw [trace_history_heads]
  simp

theorem copyTrace_history_visitedPositions
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source)
    (history : Tape source.RuleId) (word : List Symbol) :
    ExecutionTrace.visitedPositions
      (fun state : Simulator.Configuration source => state.tape .history)
      (copyTrace normal history word) = {history.head} := by
  unfold ExecutionTrace.visitedPositions
  rw [copyTrace_history_heads]
  ext candidate
  simp

@[simp] theorem copyTrace_work_visitedCard
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source)
    (history : Tape source.RuleId) (word : List Symbol) :
    (ExecutionTrace.visitedPositions
      (fun state : Simulator.Configuration source => state.tape .work)
      (copyTrace normal history word)).card = word.length + 2 := by
  rw [copyTrace_work_visitedPositions]
  exact Tape.delimiterTraversal_card word

@[simp] theorem copyTrace_output_visitedCard
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source)
    (history : Tape source.RuleId) (word : List Symbol) :
    (ExecutionTrace.visitedPositions
      (fun state : Simulator.Configuration source => state.tape .output)
      (copyTrace normal history word)).card = word.length + 2 := by
  rw [copyTrace_output_visitedPositions]
  exact Tape.delimiterTraversal_card word

@[simp] theorem copyTrace_history_visitedCard
    {source : Machine SourceControl Symbol}
    (normal : Standard.BennettNormalForm source)
    (history : Tape source.RuleId) (word : List Symbol) :
    (ExecutionTrace.visitedPositions
      (fun state : Simulator.Configuration source => state.tape .history)
      (copyTrace normal history word)).card = 1 := by
  rw [copyTrace_history_visitedPositions]
  simp

end Simulator.Copy.Resource

namespace Simulator.HistorySpace

/-!
## Exact history-tape geometry

The proof-facing trace below forgets control and the other two tapes.  A
history tape in the full construction has one of two shapes: `encoded n` has
records in cells `0, ..., n - 1` and scans the last one (or `-1` for `n = 0`),
whereas `rightBlank n` scans the blank cell `n`.  The latter occurs between
the two rules of a forward push or reverse pop.
-/

/-- The two physical history-tape shapes appearing in the simulator proof. -/
inductive Shape where
  | encoded (records : Nat)
  | rightBlank (records : Nat)
deriving DecidableEq, Repr

/-- Canonical representative; record values are irrelevant to tape geometry. -/
def Shape.tape : Shape → Tape Unit
  | .encoded records =>
      HistoryTape.encode (List.replicate records ())
  | .rightBlank records =>
      (HistoryTape.encode (List.replicate records ())).move .right

/-- Number of currently stored history records. -/
def Shape.records : Shape → Nat
  | .encoded records | .rightBlank records => records

@[simp] theorem Shape.head_tape_encoded (records : Nat) :
    (Shape.tape (.encoded records)).head = (records : Int) - 1 := by
  simp [Shape.tape, HistoryTape.head_encode]
  omega

@[simp] theorem Shape.head_tape_rightBlank (records : Nat) :
    (Shape.tape (.rightBlank records)).head = records := by
  simp [Shape.tape, HistoryTape.head_encode]

@[simp] theorem Shape.support_tape_encoded (records : Nat) :
    (Shape.tape (.encoded records)).nonblankPositions =
      Finset.Ico 0 (records : Int) := by
  simpa [Shape.tape] using
    HistoryTape.support_encode (List.replicate records ())

@[simp] theorem Shape.support_tape_rightBlank (records : Nat) :
    (Shape.tape (.rightBlank records)).nonblankPositions =
      Finset.Ico 0 (records : Int) := by
  change (HistoryTape.encode (List.replicate records ())).cells.support = _
  simpa [Tape.nonblankPositions] using
    HistoryTape.support_encode (List.replicate records ())

@[simp] theorem Shape.nonblankCard_tape_encoded (records : Nat) :
    (Shape.tape (.encoded records)).nonblankPositions.card = records := by
  simp

@[simp] theorem Shape.nonblankCard_tape_rightBlank (records : Nat) :
    (Shape.tape (.rightBlank records)).nonblankPositions.card = records := by
  simp

@[simp] theorem Shape.nonblankCard_tape (shape : Shape) :
    (Shape.tape shape).nonblankPositions.card = shape.records := by
  cases shape <;> simp [Shape.records]

/-- Equality of precisely the tape data relevant to this cost model. -/
structure SameGeometry {First Second : Type*}
    (first : Tape First) (second : Tape Second) : Prop where
  head : first.head = second.head
  support : first.nonblankPositions = second.nonblankPositions

theorem sameGeometry_encode {RuleId : Type*} (history : List RuleId) :
    SameGeometry (HistoryTape.encode history)
      (Shape.tape (.encoded history.length)) := by
  constructor
  · simp [HistoryTape.head_encode]
    omega
  · rw [HistoryTape.support_encode]
    simp

theorem sameGeometry_rightBlank {RuleId : Type*} (history : List RuleId) :
    SameGeometry ((HistoryTape.encode history).move .right)
      (Shape.tape (.rightBlank history.length)) := by
  constructor
  · simp [HistoryTape.head_encode]
  · change (HistoryTape.encode history).nonblankPositions =
      (HistoryTape.encode
        (List.replicate history.length ())).nonblankPositions
    rw [HistoryTape.support_encode, HistoryTape.support_encode]
    simp

/-- The abstraction is exact for stable forward-phase configurations. -/
theorem sameGeometry_forwardConfiguration
    {SourceControl Symbol : Type}
    (source : Machine SourceControl Symbol)
    (state : HistoryState
      (Bennett.Turing.Configuration SourceControl Symbol) source.RuleId) :
    SameGeometry
      ((forwardConfiguration source state).tape .history)
      (Shape.tape (.encoded state.history.length)) := by
  exact sameGeometry_encode state.history

/-- The abstraction is exact between the two rules of a forward push. -/
theorem sameGeometry_forwardMiddle
    {SourceControl Symbol : Type}
    (source : Machine SourceControl Symbol) (ruleId : source.RuleId)
    (state : HistoryState
      (Bennett.Turing.Configuration SourceControl Symbol) source.RuleId) :
    SameGeometry
      ((forwardMiddle source ruleId state).tape .history)
      (Shape.tape (.rightBlank state.history.length)) := by
  exact sameGeometry_rightBlank state.history

/-- The abstraction is exact for stable reverse-phase configurations. -/
theorem sameGeometry_reverseConfiguration
    {SourceControl Symbol : Type}
    (source : Machine SourceControl Symbol)
    (state : HistoryState
      (Bennett.Turing.Configuration SourceControl Symbol) source.RuleId)
    (copiedOutput : Tape Symbol) :
    SameGeometry
      ((reverseConfiguration source state copiedOutput).tape .history)
      (Shape.tape (.encoded state.history.length)) := by
  exact sameGeometry_encode state.history

/-- The abstraction is exact between the two rules of a reverse pop. -/
theorem sameGeometry_reverseMiddle
    {SourceControl Symbol : Type}
    (source : Machine SourceControl Symbol) (ruleId : source.RuleId)
    (before : Bennett.Turing.Configuration SourceControl Symbol)
    (history : List source.RuleId) (copiedOutput : Tape Symbol) :
    SameGeometry
      ((reverseMiddle source ruleId before history copiedOutput).tape .history)
      (Shape.tape (.rightBlank history.length)) := by
  exact sameGeometry_rightBlank history

/-- Copy-phase configurations retain the supplied history tape literally. -/
theorem copyConfiguration_history_sameGeometry
    {SourceControl Symbol : Type}
    (source : Machine SourceControl Symbol)
    (control : Control SourceControl source.RuleId)
    (work output : Tape Symbol) (history : List source.RuleId) :
    SameGeometry
      ((Copy.configuration source control work (HistoryTape.encode history)
        output).tape .history)
      (Shape.tape (.encoded history.length)) := by
  exact sameGeometry_encode history

/-- Two target states contributed by each source step during computation. -/
def forwardStates (sourceSteps : Nat) : List Shape :=
  (List.range sourceSteps).flatMap fun records =>
    [.rightBlank records, .encoded (records + 1)]

/-- Two target states contributed by each source step during cleanup. -/
def reverseStates (sourceSteps : Nat) : List Shape :=
  (List.range sourceSteps).reverse.flatMap fun records =>
    [.rightBlank records, .encoded records]

/--
Exact history projection of a full compute--copy--retrace state trace.

There are `2v` compute transitions, `copyTransitions` copy transitions, and
`2v` retrace transitions.  Copy states all retain the full `v`-record tape.
This is the canonical phase projection justified by the geometry bridge
lemmas above; it is not claimed here to be automatically extracted from an
arbitrary `Quadruple.Scheduled` witness.
-/
def trace (sourceSteps copyTransitions : Nat) : ExecutionTrace Shape where
  initial := .encoded 0
  subsequent :=
    forwardStates sourceSteps ++
      List.replicate copyTransitions (.encoded sourceSteps) ++
      reverseStates sourceSteps

@[simp] theorem forwardStates_length (sourceSteps : Nat) :
    (forwardStates sourceSteps).length = 2 * sourceSteps := by
  simp [forwardStates, List.length_flatMap]
  omega

@[simp] theorem reverseStates_length (sourceSteps : Nat) :
    (reverseStates sourceSteps).length = 2 * sourceSteps := by
  simp [reverseStates, List.length_flatMap]
  omega

@[simp] theorem transitionCount_trace (sourceSteps copyTransitions : Nat) :
    (trace sourceSteps copyTransitions).transitionCount =
      4 * sourceSteps + copyTransitions := by
  simp [trace, ExecutionTrace.transitionCount]
  omega

@[simp] theorem stateCount_trace (sourceSteps copyTransitions : Nat) :
    (trace sourceSteps copyTransitions).states.length =
      4 * sourceSteps + copyTransitions + 1 := by
  rw [ExecutionTrace.states_length, transitionCount_trace]

theorem mem_forwardStates_iff {sourceSteps : Nat} {shape : Shape} :
    shape ∈ forwardStates sourceSteps ↔
      ∃ records < sourceSteps,
        shape = .rightBlank records ∨ shape = .encoded (records + 1) := by
  simp [forwardStates]

theorem mem_reverseStates_iff {sourceSteps : Nat} {shape : Shape} :
    shape ∈ reverseStates sourceSteps ↔
      ∃ records < sourceSteps,
        shape = .rightBlank records ∨ shape = .encoded records := by
  simp [reverseStates]

theorem mem_states_trace_iff
    {sourceSteps copyTransitions : Nat} {shape : Shape} :
    shape ∈ (trace sourceSteps copyTransitions).states ↔
      shape = .encoded 0 ∨
      shape ∈ forwardStates sourceSteps ∨
      (copyTransitions ≠ 0 ∧ shape = .encoded sourceSteps) ∨
      shape ∈ reverseStates sourceSteps := by
  simp [ExecutionTrace.states, trace, or_assoc, or_comm]

theorem records_le_of_mem_states
    {sourceSteps copyTransitions : Nat} {shape : Shape}
    (hshape : shape ∈ (trace sourceSteps copyTransitions).states) :
    shape.records ≤ sourceSteps := by
  rw [mem_states_trace_iff] at hshape
  rcases hshape with hinitial | hforward | hcopy | hreverse
  · subst shape
    simp [Shape.records]
  · obtain ⟨records, hrecords, rfl | rfl⟩ :=
      mem_forwardStates_iff.mp hforward <;> simp [Shape.records] <;> omega
  · rcases hcopy with ⟨_, rfl⟩
    rfl
  · obtain ⟨records, hrecords, rfl | rfl⟩ :=
      mem_reverseStates_iff.mp hreverse <;> simp [Shape.records] <;> omega

/-- The full `v`-record state occurs, including when `v = 0`. -/
theorem encoded_sourceSteps_mem_states
    (sourceSteps copyTransitions : Nat) :
    .encoded sourceSteps ∈ (trace sourceSteps copyTransitions).states := by
  cases sourceSteps with
  | zero => exact mem_states_trace_iff.mpr (Or.inl rfl)
  | succ records =>
      apply mem_states_trace_iff.mpr
      exact Or.inr (Or.inl (mem_forwardStates_iff.mpr
        ⟨records, by omega, Or.inr rfl⟩))

/-- Every live record cell lies in the eventual `0, ..., v - 1` interval. -/
theorem support_subset_of_mem_states
    {sourceSteps copyTransitions : Nat} {shape : Shape}
    (hshape : shape ∈ (trace sourceSteps copyTransitions).states) :
    (Shape.tape shape).nonblankPositions ⊆
      Finset.Ico 0 (sourceSteps : Int) := by
  have hrecords := records_le_of_mem_states hshape
  cases shape <;> simp [Shape.records] at hrecords <;>
    intro position hposition <;> simp at hposition ⊢ <;> omega

theorem mem_headValues_trace_iff
    {sourceSteps copyTransitions : Nat} {position : Int} :
    position ∈
        ((trace sourceSteps copyTransitions).states.map
          fun shape => (Shape.tape shape).head) ↔
      -1 ≤ position ∧ position ≤ (sourceSteps : Int) - 1 := by
  constructor
  · intro hposition
    obtain ⟨shape, hshape, hhead⟩ := List.mem_map.mp hposition
    rw [mem_states_trace_iff] at hshape
    rcases hshape with hinitial | hforward | hcopy | hreverse
    · subst shape
      simp at hhead
      omega
    · subst position
      obtain ⟨records, hrecords, rfl | rfl⟩ :=
        mem_forwardStates_iff.mp hforward
      · simp
        omega
      · simp
        omega
    · rcases hcopy with ⟨_, rfl⟩
      simp at hhead
      omega
    · subst position
      obtain ⟨records, hrecords, rfl | rfl⟩ :=
        mem_reverseStates_iff.mp hreverse
      · simp
        omega
      · simp
        omega
  · rintro ⟨hlower, hupper⟩
    by_cases hminus : position = -1
    · apply List.mem_map.mpr
      exact ⟨.encoded 0, mem_states_trace_iff.mpr (Or.inl rfl),
        by simp [hminus]⟩
    · apply List.mem_map.mpr
      have hnonneg : 0 ≤ position := by omega
      let records := position.toNat
      have hrecordsInt : (records : Int) = position := by
        simp [records, Int.toNat_of_nonneg hnonneg]
      have hrecords : records < sourceSteps := by omega
      exact ⟨.rightBlank records,
        mem_states_trace_iff.mpr (Or.inr (Or.inl
          (mem_forwardStates_iff.mpr
            ⟨records, hrecords, Or.inl rfl⟩))),
        by simp [hrecordsInt]⟩

/-- Exactly cells from the initial `-1` through `v - 1` are scanned. -/
theorem visitedPositions_trace (sourceSteps copyTransitions : Nat) :
    ExecutionTrace.visitedPositions Shape.tape
        (trace sourceSteps copyTransitions) =
      Finset.Icc (-1) ((sourceSteps : Int) - 1) := by
  ext position
  simp [ExecutionTrace.visitedPositions, mem_headValues_trace_iff]

/-- Exact distinct history-head footprint, including the initial blank cell. -/
@[simp] theorem visitedPositions_card_trace
    (sourceSteps copyTransitions : Nat) :
    (ExecutionTrace.visitedPositions Shape.tape
      (trace sourceSteps copyTransitions)).card = sourceSteps + 1 := by
  rw [visitedPositions_trace, Int.card_Icc]
  omega

private theorem foldl_max_le (values : List Nat) (initial bound : Nat)
    (hinitial : initial ≤ bound)
    (hvalues : ∀ value ∈ values, value ≤ bound) :
    values.foldl max initial ≤ bound := by
  induction values generalizing initial with
  | nil => simpa using hinitial
  | cons value values ih =>
      simp only [List.foldl_cons]
      apply ih
      · exact max_le hinitial (hvalues value (by simp))
      · intro tailValue htail
        exact hvalues tailValue (by simp [htail])

private theorem initial_le_foldl_max (values : List Nat) (initial : Nat) :
    initial ≤ values.foldl max initial := by
  induction values generalizing initial with
  | nil => rfl
  | cons value values ih =>
      simp only [List.foldl_cons]
      exact le_trans (Nat.le_max_left initial value)
        (ih (max initial value))

private theorem mem_le_foldl_max (values : List Nat) (initial value : Nat)
    (hvalue : value ∈ values) :
    value ≤ values.foldl max initial := by
  induction values generalizing initial with
  | nil => simp at hvalue
  | cons head tail ih =>
      simp only [List.foldl_cons]
      rcases List.mem_cons.mp hvalue with rfl | htail
      · exact le_trans (Nat.le_max_right initial value)
          (initial_le_foldl_max tail (max initial value))
      · exact ih (max initial head) htail

/-- At peak occupancy, records occupy exactly cells `0, ..., v - 1`. -/
theorem peakSupport (sourceSteps : Nat) :
    (Shape.tape (.encoded sourceSteps)).nonblankPositions =
      Finset.Ico 0 (sourceSteps : Int) := by
  simp

/-- Exact maximum simultaneously nonblank history cells over the full trace. -/
@[simp] theorem maximumNonblankCells_trace
    (sourceSteps copyTransitions : Nat) :
    ExecutionTrace.maximumNonblankCells Shape.tape
      (trace sourceSteps copyTransitions) = sourceSteps := by
  unfold ExecutionTrace.maximumNonblankCells
  let states := (trace sourceSteps copyTransitions).states
  let counts := states.map fun shape =>
    (Shape.tape shape).nonblankPositions.card
  have hfold : counts.foldl max 0 =
      states.foldl
        (fun peak shape => max peak
          (Shape.tape shape).nonblankPositions.card) 0 := by
    simp [counts, List.foldl_map]
  change states.foldl
    (fun peak shape => max peak
      (Shape.tape shape).nonblankPositions.card) 0 = sourceSteps
  rw [← hfold]
  apply Nat.le_antisymm
  · apply foldl_max_le counts 0 sourceSteps
    · simp
    · intro count hcount
      obtain ⟨shape, hshape, rfl⟩ := List.mem_map.mp hcount
      rw [Shape.nonblankCard_tape]
      change shape ∈ (trace sourceSteps copyTransitions).states at hshape
      exact records_le_of_mem_states hshape
  · have hpeak := mem_le_foldl_max
      counts 0 sourceSteps
      (List.mem_map.mpr
        ⟨.encoded sourceSteps,
          by
            change .encoded sourceSteps ∈
              (trace sourceSteps copyTransitions).states
            exact encoded_sourceSteps_mem_states
              sourceSteps copyTransitions,
          by simp⟩)
    exact hpeak

private theorem mem_foldl_union_support
    (states : List Shape) (initial : Finset Int) (position : Int) :
    position ∈ states.foldl
        (fun positions shape =>
          positions ∪ (Shape.tape shape).nonblankPositions) initial ↔
      position ∈ initial ∨
        ∃ shape ∈ states,
          position ∈ (Shape.tape shape).nonblankPositions := by
  induction states generalizing initial with
  | nil => simp
  | cons shape states ih =>
      rw [List.foldl_cons, ih]
      simp only [Finset.mem_union, List.mem_cons]
      aesop

/-- Exactly cells `0, ..., v - 1` hold a record at some time. -/
theorem everNonblankPositions_trace (sourceSteps copyTransitions : Nat) :
    ExecutionTrace.everNonblankPositions Shape.tape
        (trace sourceSteps copyTransitions) =
      Finset.Ico 0 (sourceSteps : Int) := by
  ext position
  unfold ExecutionTrace.everNonblankPositions
  rw [mem_foldl_union_support]
  simp only [Finset.notMem_empty, false_or, Finset.mem_Ico]
  constructor
  · rintro ⟨shape, hshape, hposition⟩
    simpa using support_subset_of_mem_states hshape hposition
  · intro hposition
    exact ⟨.encoded sourceSteps,
      encoded_sourceSteps_mem_states sourceSteps copyTransitions,
      by simpa using hposition⟩

/-- Head scans already contain the entire ever-nonblank history footprint. -/
theorem footprintPositions_trace (sourceSteps copyTransitions : Nat) :
    ExecutionTrace.footprintPositions Shape.tape
        (trace sourceSteps copyTransitions) =
      Finset.Icc (-1) ((sourceSteps : Int) - 1) := by
  rw [ExecutionTrace.footprintPositions, visitedPositions_trace,
    everNonblankPositions_trace]
  apply Finset.union_eq_left.mpr
  intro position hposition
  simp at hposition ⊢
  omega

@[simp] theorem footprintPositions_card_trace
    (sourceSteps copyTransitions : Nat) :
    (ExecutionTrace.footprintPositions Shape.tape
      (trace sourceSteps copyTransitions)).card = sourceSteps + 1 := by
  rw [footprintPositions_trace, Int.card_Icc]
  omega

/-!
### Specialization to the concrete copy loop

For an output word of length `lambda`, copying takes
`4 * lambda + 5` transitions.  The substitution below yields the full time
formula while leaving every history-space measure independent of `lambda`.
-/

@[simp] theorem transitionCount_concreteTrace
    (sourceSteps outputLength : Nat) :
    (trace sourceSteps (4 * outputLength + 5)).transitionCount =
      4 * sourceSteps + 4 * outputLength + 5 := by
  simp
  omega

@[simp] theorem stateCount_concreteTrace
    (sourceSteps outputLength : Nat) :
    (trace sourceSteps (4 * outputLength + 5)).states.length =
      4 * sourceSteps + 4 * outputLength + 6 := by
  simp
  omega

/-- Exact history-tape cost of the concrete compute--copy--retrace trace. -/
theorem concreteTrace_history_cost (sourceSteps outputLength : Nat) :
    ExecutionTrace.visitedPositions Shape.tape
        (trace sourceSteps (4 * outputLength + 5)) =
        Finset.Icc (-1) ((sourceSteps : Int) - 1) ∧
      (ExecutionTrace.visitedPositions Shape.tape
        (trace sourceSteps (4 * outputLength + 5))).card = sourceSteps + 1 ∧
      ExecutionTrace.everNonblankPositions Shape.tape
        (trace sourceSteps (4 * outputLength + 5)) =
        Finset.Ico 0 (sourceSteps : Int) ∧
      ExecutionTrace.maximumNonblankCells Shape.tape
        (trace sourceSteps (4 * outputLength + 5)) = sourceSteps := by
  exact ⟨visitedPositions_trace _ _, visitedPositions_card_trace _ _,
    everNonblankPositions_trace _ _, maximumNonblankCells_trace _ _⟩

end Simulator.HistorySpace
end Bennett.Turing
