import Bennett.Turing.Simulator.Core
import Mathlib.Data.Fintype.EquivFin
import Mathlib.Data.Fintype.Sum
import Mathlib.Tactic.DeriveFintype
import Mathlib.Tactic.FinCases

/-!
# Proof-facing syntax and exact Table 1 cardinalities

The semantic rule families use constructors rather than numeric positions.
An explicit equivalence can later transport this family to the intrinsic
`Fin ruleCount` representation of `QuadrupleMachine`; none of the proofs below
depends on that enumeration.
-/

namespace Bennett.Turing
namespace Simulator

variable {SourceControl SourceRuleId Symbol : Type}

/-- The two forward quadruples generated by one source quintuple. -/
inductive ForwardRuleId (SourceRuleId : Type) where
  | rewrite (ruleId : SourceRuleId)
  | moveRecord (ruleId : SourceRuleId)
deriving DecidableEq, Fintype, Repr

/-- Five fixed copy rules and two letter-indexed rule families. -/
inductive CopyRuleId (Symbol : Type) where
  | enter
  | moveRight
  | copySymbol (symbol : Symbol)
  | turn
  | moveLeft
  | checkSymbol (symbol : Symbol)
  | exit
deriving DecidableEq, Fintype, Repr

/-- The two retrace quadruples generated by one source quintuple. -/
inductive ReverseRuleId (SourceRuleId : Type) where
  | eraseRecordMove (ruleId : SourceRuleId)
  | restoreSymbol (ruleId : SourceRuleId)
deriving DecidableEq, Fintype, Repr

/-- Structurally disjoint identifier family for every rule in Table 1. -/
inductive TableRuleId (SourceRuleId Symbol : Type) where
  | forward (rule : ForwardRuleId SourceRuleId)
  | copy (rule : CopyRuleId Symbol)
  | reverse (rule : ReverseRuleId SourceRuleId)
deriving DecidableEq, Fintype, Repr

def controlEquiv {SourceControl SourceRuleId : Type} :
    Control SourceControl SourceRuleId ≃
      (SourceControl ⊕ SourceRuleId) ⊕
        (Fin 4 ⊕ (SourceControl ⊕ SourceRuleId)) where
  toFun
    | .forward control => .inl (.inl control)
    | .forwardConnector ruleId => .inl (.inr ruleId)
    | .copyRightMove => .inr (.inl 0)
    | .copyRightRead => .inr (.inl 1)
    | .copyLeftMove => .inr (.inl 2)
    | .copyLeftRead => .inr (.inl 3)
    | .reverse control => .inr (.inr (.inl control))
    | .reverseConnector ruleId => .inr (.inr (.inr ruleId))
  invFun
    | .inl (.inl control) => .forward control
    | .inl (.inr ruleId) => .forwardConnector ruleId
    | .inr (.inl ⟨0, _⟩) => .copyRightMove
    | .inr (.inl ⟨1, _⟩) => .copyRightRead
    | .inr (.inl ⟨2, _⟩) => .copyLeftMove
    | .inr (.inl ⟨3, _⟩) => .copyLeftRead
    | .inr (.inr (.inl control)) => .reverse control
    | .inr (.inr (.inr ruleId)) => .reverseConnector ruleId
  left_inv control := by cases control <;> rfl
  right_inv encoded := by
    rcases encoded with encoded | encoded
    · rcases encoded with control | ruleId <;> rfl
    · rcases encoded with index | encoded
      · fin_cases index <;> rfl
      · rcases encoded with control | ruleId <;> rfl

instance {SourceControl SourceRuleId : Type}
    [Fintype SourceControl] [Fintype SourceRuleId] :
    Fintype (Control SourceControl SourceRuleId) :=
  Fintype.ofEquiv _ controlEquiv.symm

def forwardRuleIdEquiv {SourceRuleId : Type} :
    ForwardRuleId SourceRuleId ≃ SourceRuleId ⊕ SourceRuleId where
  toFun
    | .rewrite ruleId => .inl ruleId
    | .moveRecord ruleId => .inr ruleId
  invFun
    | .inl ruleId => .rewrite ruleId
    | .inr ruleId => .moveRecord ruleId
  left_inv rule := by cases rule <;> rfl
  right_inv rule := by cases rule <;> rfl

def copyRuleIdEquiv {Symbol : Type} :
    CopyRuleId Symbol ≃ Fin 5 ⊕ (Symbol ⊕ Symbol) where
  toFun
    | .enter => .inl 0
    | .moveRight => .inl 1
    | .copySymbol symbol => .inr (.inl symbol)
    | .turn => .inl 2
    | .moveLeft => .inl 3
    | .checkSymbol symbol => .inr (.inr symbol)
    | .exit => .inl 4
  invFun
    | .inl ⟨0, _⟩ => .enter
    | .inl ⟨1, _⟩ => .moveRight
    | .inl ⟨2, _⟩ => .turn
    | .inl ⟨3, _⟩ => .moveLeft
    | .inl ⟨4, _⟩ => .exit
    | .inr (.inl symbol) => .copySymbol symbol
    | .inr (.inr symbol) => .checkSymbol symbol
  left_inv rule := by cases rule <;> rfl
  right_inv encoded := by
    rcases encoded with index | encoded
    · fin_cases index <;> rfl
    · rcases encoded with symbol | symbol <;> rfl

def reverseRuleIdEquiv {SourceRuleId : Type} :
    ReverseRuleId SourceRuleId ≃ SourceRuleId ⊕ SourceRuleId where
  toFun
    | .eraseRecordMove ruleId => .inl ruleId
    | .restoreSymbol ruleId => .inr ruleId
  invFun
    | .inl ruleId => .eraseRecordMove ruleId
    | .inr ruleId => .restoreSymbol ruleId
  left_inv rule := by cases rule <;> rfl
  right_inv rule := by cases rule <;> rfl

def tableRuleIdEquiv {SourceRuleId Symbol : Type} :
    TableRuleId SourceRuleId Symbol ≃
      ForwardRuleId SourceRuleId ⊕
        (CopyRuleId Symbol ⊕ ReverseRuleId SourceRuleId) where
  toFun
    | .forward rule => .inl rule
    | .copy rule => .inr (.inl rule)
    | .reverse rule => .inr (.inr rule)
  invFun
    | .inl rule => .forward rule
    | .inr (.inl rule) => .copy rule
    | .inr (.inr rule) => .reverse rule
  left_inv rule := by cases rule <;> rfl
  right_inv rule := by rcases rule with rule | rule <;> cases rule <;> rfl

@[simp] theorem control_card [Fintype SourceControl] [Fintype SourceRuleId] :
    Fintype.card (Control SourceControl SourceRuleId) =
      2 * Fintype.card SourceControl + 2 * Fintype.card SourceRuleId + 4 := by
  rw [Fintype.card_congr controlEquiv]
  simp
  omega

@[simp] theorem forwardRuleId_card [Fintype SourceRuleId] :
    Fintype.card (ForwardRuleId SourceRuleId) =
      2 * Fintype.card SourceRuleId := by
  rw [Fintype.card_congr forwardRuleIdEquiv]
  simp
  omega

@[simp] theorem copyRuleId_card [Fintype Symbol] :
    Fintype.card (CopyRuleId Symbol) = 2 * Fintype.card Symbol + 5 := by
  rw [Fintype.card_congr copyRuleIdEquiv]
  simp
  omega

@[simp] theorem reverseRuleId_card [Fintype SourceRuleId] :
    Fintype.card (ReverseRuleId SourceRuleId) =
      2 * Fintype.card SourceRuleId := by
  rw [Fintype.card_congr reverseRuleIdEquiv]
  simp
  omega

/-- Exact Table 1 rule count, with `Symbol` containing only nonblank letters. -/
@[simp] theorem tableRuleId_card [Fintype SourceRuleId] [Fintype Symbol] :
    Fintype.card (TableRuleId SourceRuleId Symbol) =
      4 * Fintype.card SourceRuleId +
        2 * (Fintype.card Symbol + 1) + 3 := by
  rw [Fintype.card_congr tableRuleIdEquiv]
  simp
  omega

/-- Table 1's `4N + 2z + 3`, where `z` includes the distinguished blank. -/
theorem tableRuleId_card_fullAlphabet
    [Fintype SourceRuleId] [Fintype Symbol] :
    Fintype.card (TableRuleId SourceRuleId Symbol) =
      4 * Fintype.card SourceRuleId +
        2 * Fintype.card (TapeSymbol Symbol) + 3 := by
  simp

end Simulator
end Bennett.Turing
